server:
  port: 8080

spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

mybatis-plus:
  mapper-locations: classpath:**/*.xml
#  type-aliases-package: com.yourcompany.yourproject.domain
  global-config:
    db-config:
#      id-type: auto
#      table-prefix: t_  # ????????????????????
      logic-delete-value: 1
      logic-not-delete-value: 0
      # ?????????????????????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false  # ????????????????







